## Client test - network timeout with application timeout

### Setup

The test is started with a two node sharded cluster. Then, traffic to one
of the nodes is blackholed via the firewall simulating the node disappearing
ungracefully.

### Log

<pre>
speed% be ruby test_client.rb config/app-timeout.yml
2019-08-30 19:42:43 -0400: 718 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=3 avail=2 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=4 avail=1 pending=0>>]>
2019-08-30 19:42:44 -0400: 788 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=1 avail=4 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>]>
2019-08-30 19:42:45 -0400: 776 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=1 avail=4 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=3 avail=2 pending=0>>]>
2019-08-30 19:42:46 -0400: 758 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=4 avail=1 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=4 avail=1 pending=0>>]>
2019-08-30 19:42:47 -0400: 773 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=4 avail=1 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=1 avail=4 pending=0>>]>
2019-08-30 19:42:48 -0400: 779 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=4 avail=1 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=4 avail=1 pending=0>>]>
2019-08-30 19:42:49 -0400: 763 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=2 avail=3 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=4 avail=1 pending=0>>]>
2019-08-30 19:42:50 -0400: 769 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=2 avail=3 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=2 avail=3 pending=0>>]>
2019-08-30 19:42:51 -0400: 770 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=2 avail=3 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=3 avail=2 pending=0>>]>
2019-08-30 19:42:52 -0400: 761 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=4 avail=1 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=2 avail=3 pending=0>>]>
2019-08-30 19:42:53 -0400: 321 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:42:54 -0400: 0 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:42:55 -0400: 0 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:42:56 -0400: 0 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:42:57 -0400: 0 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:42:58 -0400: 0 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:42:59 -0400: 0 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:00 -0400: 0 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:01 -0400: 0 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:02 -0400: 0 read ops, 21 alive threads, 0 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
Unhandled exception in thread reader-9: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-5: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-11: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-1: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-0: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-15: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-14: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-6: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-18: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-2: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-4: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-12: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-16: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-7: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-19: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
2019-08-30 19:43:03 -0400: 16 read ops, 21 alive threads, 15 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:04 -0400: 0 read ops, 21 alive threads, 15 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:05 -0400: 0 read ops, 21 alive threads, 15 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:06 -0400: 0 read ops, 21 alive threads, 15 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:07 -0400: 0 read ops, 21 alive threads, 15 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:08 -0400: 0 read ops, 21 alive threads, 15 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:09 -0400: 0 read ops, 21 alive threads, 15 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:10 -0400: 0 read ops, 21 alive threads, 15 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
W, [2019-08-30T19:43:11.595728 #24573]  WARN -- : Retrying ismaster in monitor for localhost:14440 due to: Mongo::Error::SocketTimeoutError Errno::ETIMEDOUT: Connection timed out - Took more than 10 seconds to receive data (for 127.0.0.1:14440 (no TLS))
2019-08-30 19:43:11 -0400: 0 read ops, 21 alive threads, 15 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:12 -0400: 0 read ops, 21 alive threads, 15 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
Unhandled exception in thread reader-5: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-1: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-9: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-14: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-6: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-15: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-0: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-12: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-16: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-18: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-2: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-7: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-11: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-4: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-19: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
2019-08-30 19:43:13 -0400: 24 read ops, 21 alive threads, 30 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:14 -0400: 0 read ops, 21 alive threads, 30 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:15 -0400: 0 read ops, 21 alive threads, 30 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:16 -0400: 0 read ops, 21 alive threads, 30 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:17 -0400: 0 read ops, 21 alive threads, 30 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:18 -0400: 0 read ops, 21 alive threads, 30 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:19 -0400: 0 read ops, 21 alive threads, 30 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:20 -0400: 0 read ops, 21 alive threads, 30 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 MONGOS pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:21 -0400: 0 read ops, 21 alive threads, 30 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 UNKNOWN pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
2019-08-30 19:43:22 -0400: 0 read ops, 21 alive threads, 30 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 UNKNOWN pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=0 avail=5 pending=0>>]>
Unhandled exception in thread reader-1: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-9: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-5: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-14: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-16: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-2: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-12: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-6: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-11: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-4: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-15: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-7: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-18: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-19: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
Unhandled exception in thread reader-0: Mongo::Error::ConnectionCheckOutTimeout: Timed out when attempting to check out a connection from pool for localhost:14440 after 10 sec. Connections in pool: 0 available, 5 checked out, 0 pending
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:350:in `block (2 levels) in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `loop'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:297:in `block in check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `catch'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:296:in `check_out'
/home/w/apps/ruby-driver/lib/mongo/server/connection_pool.rb:558:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/server.rb:416:in `with_connection'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:50:in `get_result'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:26:in `do_execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/executable.rb:38:in `execute'
/home/w/apps/ruby-driver/lib/mongo/operation/shared/op_msg_or_find_command.rb:28:in `execute'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:89:in `send_initial_query'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:61:in `block in read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:304:in `modern_read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:117:in `read_with_retry'
/home/w/apps/ruby-driver/lib/mongo/retryable.rb:60:in `read_with_retry_cursor'
/home/w/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `read_with_retry_cursor'
/home/w/apps/ruby-driver/lib/mongo/collection/view/iterable.rb:45:in `each'
test_client.rb:87:in `to_a'
test_client.rb:87:in `do_find_itself'
test_client.rb:82:in `do_one_find'
test_client.rb:49:in `block (2 levels) in run'
test_client.rb:108:in `block in run_thread_loop'
2019-08-30 19:43:23 -0400: 446 read ops, 21 alive threads, 45 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 UNKNOWN pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=4 avail=1 pending=0>>]>
2019-08-30 19:43:24 -0400: 772 read ops, 21 alive threads, 45 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 UNKNOWN pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=4 avail=1 pending=0>>]>
2019-08-30 19:43:25 -0400: 771 read ops, 21 alive threads, 45 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 UNKNOWN pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=4 avail=1 pending=0>>]>
2019-08-30 19:43:26 -0400: 768 read ops, 21 alive threads, 45 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 UNKNOWN pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=3 avail=2 pending=0>>]>
2019-08-30 19:43:27 -0400: 757 read ops, 21 alive threads, 45 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 UNKNOWN pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=4 avail=1 pending=0>>]>
2019-08-30 19:43:28 -0400: 776 read ops, 21 alive threads, 45 exceptions
#<Cluster topology=Sharded[localhost:14440,localhost:14441] servers=[#<Server address=localhost:14440 UNKNOWN pool=#<ConnectionPool size=5 (0-5) used=5 avail=0 pending=0>>,#<Server address=localhost:14441 MONGOS pool=#<ConnectionPool size=5 (0-5) used=4 avail=1 pending=0>>]>
</pre>

### Analysis

When one of the two nodes in a deployment disappears, the application
experiences a ~20 second outage when no finds are performed. From 19:42:53 to
19:43:21, the driver believes it is connected to two mongos nodes and
is randomly selecting between them for operations. Since one of the nodes
is unavailable, operations being sent there are stuck. It takes 18 seconds,
which is just under two heartbeat intervals (2*10 seconds) for the driver
to change status of 14440 to unknown, at which point it no longer routes
operations to it. 3 seconds later, at 19:43:24, in flight operations to
14440 time out and all new operations are sent to 14441 only, and application
availability is restored.

The application experiences a complete outage even though there is at least
one functioning node at any given time because each thread randomly selects
a server for its operations, and within the 20 second reaction time of the
driver to the disappearance of 14440 each thread manages to initiate an
operation with 1440 selected as target, thus each thread gets stuck producing
a total application outage.
